version: '3'
services:
  build:
    image:  blockchain-build
    build:
      context: .
      dockerfile: Dockerfile-build
    volumes:
      # uid and gid in the Dockerfile-build must match the system user uid and gid
      - "${HOME}/.stack:/home/buildusr/.stack"
      - .:/workspace
    user: "1000"
    entrypoint:
      - /bin/sh
      - -c
      - 'stack -v --install-ghc clean && (cd blockchain-ui-fe && npm install && ng build --env=prod) && stack-build upx'

  beacon-node:
    image: carbolymer/blockchain-node
    build:
      context: .
      dockerfile: Dockerfile-run
    hostname: beacon-node

  drone-node:
    image: carbolymer/blockchain-node
    build:
      context: .
      dockerfile: Dockerfile-run
    depends_on:
      - beacon-node

  ui:
    image: carbolymer/blockchain-node
    build:
      context: .
      dockerfile: Dockerfile-run
    restart: on-failure
    depends_on:
      - beacon-node
    ports:
      - "8000:8000"
    entrypoint:
      - /usr/local/bin/blockchain-ui-exe
      - "8000"
      - "http://beacon-node:8000/"
      - "/srv"
